### ISSUE TITLE
ReferenceError: validateStatus is not defined

### ISSUE THREAD

**Issue by seba627** [ob1y2k/publitio_js_sdk#9]
In versions 1.0.9 and 1.0.10 after call **uploadFile** method, the library throws the error
```ReferenceError: validateStatus is not defined```

**Code**
```
const publitio = new PublitioAPI(process.env.PUBLITIO_API_KEY, process.env.PUBLITIO_API_SECRET)

...

const file = fs.readFileSync("uploads/" + req.file.filename)
publitio.uploadFile(file, 'file')
```

With version 1.0.8 works

**Comment by ennmichael** [comment]
Hi @seba627, thanks a lot for opening the issue.
It appears I had a typo and somehow missed it.
Anyways, try installing version 1.1.0 of this package from npm, and hopefully the error will be resolved.
Sorry for the wait and inconvenience, and if you run into any other problems in the future, please open more issues!
Thank you.
